apiVersion: v1
kind: Pod
metadata:
  name: my-order
  namespace: default
  labels:
    app: order
    version: v1
spec:
  containers:
    - name: order
      image: hub.anicert.cn/library/my-order:1.0.1
      imagePullPolicy: IfNotPresent
      #readinessProbe:
        #httpGet:
          #port: 8082
          #path: /storage/status
        #initialDelaySeconds: 1
        #periodSeconds: 3
      readinessProbe:
        tcpSocket:
          host: 192.168.8.89
          port: 8848
        initialDelaySeconds: 1
        periodSeconds: 3
        timeoutSeconds: 5
      livenessProbe:
        httpGet:
          port: 8081
          path: /order/status
        initialDelaySeconds: 120
        periodSeconds: 60
        timeoutSeconds: 5


